env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
before:
  hooks:
    - ./check.sh
builds:
  - id: cfssl-linux
    binary: cfssl
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - completions/goreleaser.$goarch
archives:
  - format: binary
release:
  github:
    owner: Abhisheknishant
    name: cfssl
  prerelease: auto
changelog:
  sort: asc
