env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - id: cfssl-linux
    binary: cfssl
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-linux-arm64
    binary: cfssl
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/aarch64-linux-gnu-gcc
  - id: cfssl-windows
    binary: cfssl
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}} 
archives:
  - format: binary
release:
  github:
    owner: Abhisheknishant
    name: cfssl
  prerelease: auto
changelog:
  sort: asc
