env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - GOFLAGS=-mod=vendor
  - GOPROXY=off
builds:
  - id: cfssl-linux
    binary: cfssl
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-linux-arm64
    binary: cfssl
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/cfssl
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=aarch64-linux-gnu-gcc
  - id: cfssl-bundle-linux
    binary: cfssl-bundle
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl-bundle
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-certinfo-linux
    binary: cfssl-certinfo
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl-certinfo
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-certinfo-linux-arm64
    binary: cfssl-certinfo
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/cfssl-certinfo
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=aarch64-linux-gnu-gcc
  - id: cfssl-newkey-linux
    binary: cfssl-newkey
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl-newkey
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssl-scan-linux
    binary: cfssl-scan
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssl-scan
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssljson-linux
    binary: cfssljson
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/cfssljson
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: cfssljson-linux-arm64
    binary: cfssljson
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/cfssljson
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=aarch64-linux-gnu-gcc
  - id: mkbundle-linux
    binary: mkbundle
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/mkbundle
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
  - id: multirootca-linux
    binary: multirootca
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/multirootca
    ldflags:
      - -s -w -X github.com/cloudflare/cfssl/cli/version.version={{.Version}}
      - -linkmode external -extldflags "-static"
    env:
      - CC=/usr/bin/musl-gcc
archives:
  - format: binary
release:
  github:
    owner: cloudflare
    name: cfssl
  prerelease: auto
changelog:
  sort: asc
