sudo: false
language: go

matrix:
  include:
    - go: 1.12.x
      
# Only build pull requests, pushes to the master branch, and branches
# starting with `test-`. This is a convenient way to push branches to
# your own fork of the repository to ensure Travis passes before submitting
# a PR. For instance, you might run:
# git push myremote branchname:test-branchname

script:
  #- sudo apt-get install gcc-aarch64-linux-gnu
  #- make github-release
  - docker login -u sakshi9715 -p Dockersakshi12
  - make release

env:
  global:
    - secure: "OmaaZ3jhU9VQ/0SYpenUJEfnmKy/MwExkefFRpDbkRSu/hTQpxxALAZV5WEHo7gxLRMRI0pytLo7w+lAd2FlX1CNcyY62MUicta/8P2twsxp+lR3v1bJ7dwk6qsDbO7Nvv3BKPCDQCHUkggbAEJaHEQGdLk4ursNEB1aGimuCEc="
    - GO111MODULE=on
  matrix:
    - BUILD_TAGS="postgresql mysql"

after_success:
  - bash <(curl -s https://codecov.io/bash)
